version: "3.8"

services:
  laravel-app:
    build:
      context: dockerfiles
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    container_name: app_container
  mysql:
    image: mysql:8.0
    ports:
      - "5432:5432"
    environment:
      MYSQL_DATABASE: laravel-pet-db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql_container
    depends_on:
      - laravel-app

  composer:
    build:
      context: dockerfiles
      dockerfile: Dockerfile_composer
    volumes:
      - db_data:/var/www/laravel
  artisan:
    build:
      context: dockerfiles
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  db_data: