services:
    laravel-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app-cont
        ports:
            - "8000:8000"
        volumes:
            - '.:/app'
        networks:
            - sail
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: pgsql
            DB_PORT: 5432
            DB_DATABASE: laravel-pet-db
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
        depends_on:
            pgsql:
                condition: service_healthy
        command:
            - /bin/sh
            - -lc
            - >
                git config --global --add safe.directory /app &&
                composer install &&
                php artisan migrate --force &&
                php artisan serve --host=0.0.0.0 --port=8000

    pgsql:
        image: 'postgres:18-alpine'
        container_name: postgresdb
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: laravel-pet-db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - 'laravel-pet-db'
                - '-U'
                - 'postgres'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
