services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/laravel
    depends_on:
      - mysql
      - php
  php:
    build: 
      context: dockerfiles
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/laravel
    container_name: app_container
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel-pet-db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql_container

  composer:
    build:
      context: dockerfiles
      dockerfile: Dockerfile_composer
    volumes:
      - db_data:/var/www/laravel
  artisan:
    build:
      context: dockerfiles
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  db_data: